Repository tkshill/Template, pull requests merged in 2020-09, with the labels that each got.

#3 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general.md
Labels: documentation, repo management

#5 Docs: Create pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, example, for maintainers, repo management

#6 Docs: Create code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, example, for maintainers, repo management

#8 DOCS:Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, for maintainers, repo management

#9 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
